sudo: false
dist: trusty

language: python
python: 3.6
cache: pip

install:
  - python -m pip install -r requirements.txt
  - python -m pip install -U pip coverage
  - python -m pip install -U pip pytest
  - python -m pip install -U pytest-cov
  - python -m pip install -U codecov

script:
  - cd tests
  - coverage run -m pytest test_com_deliberacoes.py

after_success:
  - codecov -t "15424ed3-5356-4617-a924-69f840fa7fb8"
