sudo: false
dist: trusty

language: python
python: 3.6
cache: pip

env:
  global:
    - COVERALLS_REPO_TOKEN=jfOVeGf9SKjrecNCQ7d6vZyG5zxViVLN0

install:
  - python -m pip install -U pip coverage
  - python -m pip install -U pip coveralls
  - python -m pip install -r requirements.txt

script:
  - cd tests
  - pytest test_com_deliberacoes.py -v
  - cd ..
  - coverage run -a novedejulho/*.py test

after_success:
  - coveralls --rcfile=.coveragerc

